---
title: "Billboard Hot 100"
format: 
  dashboard: 
    logo: "images/logo.png"
    orientation: columns
---

```{r}
#|include: false

#install packages
library(httr2)
library(jsonlite)
library(tidyverse)
library(purrr)
```


## Column {width="45%"}

```{r, createtable}
#| expandable: false
generate_svg_circle <- function(popularity_value) {
  popularity_value <- as.numeric(popularity_value)

  radius <- 10 + 15 * (popularity_value / 100)
  circle_colour_picker <- colorRampPalette(c("#B91d1d", "#ED8E11", "#EDDE11", "#1DB954"))
  color <- circle_colour_picker(101)[popularity_value + 1]

  sprintf(
    '<svg height="%1$s" width="%1$s"><circle cx="%2$s" cy="%2$s" r="%2$s" stroke="none" stroke-width="0" fill="%3$s" /><text class="circle-text" x="%2$s" y="%2$s" font-size="%4$s" fill="white" text-anchor="middle" dy=".3em">%5$s</text></svg>',
    2 * radius, radius, color, radius * 0.6, popularity_value
  )
}

hot100_df |>
  select(album_art, song_name, artist_name, track_duration, popularity) |> 
  gt(id = "custom") |>
  cols_label(
    album_art = md("**Song**"),
    song_name = "",
    artist_name = md("**Artist**"),
    track_duration = html('<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="15" height="15" viewBox="0,0,255.998,255.998"><g fill="#ffffff" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(10.66667,10.66667)"><path d="M12,2c-5.523,0 -10,4.477 -10,10c0,5.523 4.477,10 10,10c5.523,0 10,-4.477 10,-10c0,-5.523 -4.477,-10 -10,-10zM14.586,16l-3.293,-3.293c-0.188,-0.188 -0.293,-0.442 -0.293,-0.707v-5c0,-0.552 0.448,-1 1,-1v0c0.552,0 1,0.448 1,1v4.586l3,3c0.39,0.39 0.39,1.024 0,1.414v0c-0.39,0.39 -1.024,0.39 -1.414,0z"></path></g></g></svg>'),
    popularity = md("**Popularity**")
  ) |>
    cols_width(
    album_art      ~ px(55),
    song_name      ~ px(190),
    artist_name    ~ px(120),
    track_duration ~ px(55),
    popularity     ~ px(80)
  ) |>
      
  # Keep the sparkline column blank (reserved for later (sparkline = ""))
  text_transform(
    locations = cells_body(columns = album_art),
    fn = function(x) { web_image(url = x, height = 50) }
  ) |>
  text_transform(
    fn = function(x) { generate_svg_circle(x) },
    locations = cells_body(columns = popularity)
  ) |>
  tab_style(
    style = cell_text(whitespace = "normal"),
    locations = cells_body(columns = c(song_name, artist_name))
  ) |>

  fmt(
    columns = track_duration,
    fns = function(x) {
      num_minutes <- floor(x / 60000)
      num_seconds <- ifelse(round((x %% 60000) / 1000) == 60, 59, round((x %% 60000) / 1000))
      sprintf("%d:%02d", num_minutes, num_seconds)
    }
  ) |>
  cols_align(
    align = "center",
    columns = popularity
  ) |>
  tab_footnote(
    footnote = "The popularity of a track is a value between 0 and 100, with 100 being the most popular. The popularity is calculated by algorithm and is based, in the most part, on the total number of plays the track has had and how recent those plays are. Generally speaking, songs that are being played a lot now will have a higher popularity than songs that were played a lot in the past.",
    locations = cells_column_labels(columns = popularity)
  ) |>
  tab_source_note(
    source_note = md("**Source:** [Billboard Hot 100 Playlist](https://open.spotify.com/playlist/6UeSakyzhiEt4NB3UAd6NQ), from the Spotify Web API")
  ) |>
  tab_options(
    table.font.color = "#FFFFFF",
    table.background.color = "#191414",
    table.font.size = px(12),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table_body.hlines.color = "transparent",
    table_body.border.bottom.color = "transparent",
    column_labels.border.bottom.color = "transparent",
    column_labels.border.top.color = "transparent",
    footnotes.background.color = "#282828",
    source_notes.background.color = "#282828"
  ) |>
  tab_style_body(
    style = cell_borders(
      sides = c("top", "bottom"),
      weight = px(0)
    ),
    fn = function(x) { is.numeric(x) | is.character(x) }
  ) |>
  opt_css(
    css = "
    table tr:nth-child(odd) {
      background-color: #282828;
    }

    table tr:hover {
      background-color: #383838;
    }

    .cell-output-display {
      overflow-x: unset !important;
    }

    div#custom {
      overflow-x: unset !important;
      overflow-y: unset !important;
    }

    #custom .gt_col_heading {
      position: sticky !important;
      top: -5px !important;
      z-index: 10 !important;
    }
    #custom .gt_table { table-layout: fixed; width: 100%; }
    "
  )
```

## Column {width="55%"}

### Row {height="10%"}

```{ojs}
//| expandable: false
hot100 = await FileAttachment("hot100_ojs.json").json()

viewof songDropdown = Inputs.select(
  hot100,
  {
    label: "Choose a song",
    format: d => d.song_name,
    unique: true
  }
)
```

### Row {height="55%"}

```{ojs}
//| expandable: false
html`<iframe class="custom-iframe" style="border-radius:12px; display: flex; justify-content: center; align-items: center;" 
  src=${`https://open.spotify.com/embed/track/${songDropdown.song_id}?utm_source=generator&theme=0`} 
  width="100%" 
  height="352" 
  frameBorder="0" 
  allowfullscreen="" 
  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
  loading="lazy">
</iframe>`
```


